### ISSUE TITLE
error in line 60

### ISSUE THREAD

**Issue by xin-xinhanggao** [mzur/pyJBU#1]
I am sorry to bother you that when I try to use the bilateral upsampling, I  meet an error at line 60
```
Traceback (most recent call last):
  File "jbu.py", line 60, in <module>
    Image.fromarray(np.array(list(result)).astype(np.uint8)).save(args.output)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 641, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
ValueError: cannot reshape array of size 100 into shape (3)
```

**Comment by mzur** [comment]
Sorry, this issue got lost somehow. Can you please provide more details (if it is still relevant)?

**Comment by xin-xinhanggao** [comment]
@mzur Hi mzur! Thanks for your kind reply, I have fixed it :) .
